version: '3'
services:
  myapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=myimg
    depends_on:
      - postgres
    networks:
      - myapp-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=myimg
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - myapp-network

volumes:
  postgres-data:

networks:
  myapp-network:
    name: myapp-network